spring:
  application:
    name: api-gateway
  config:
    import:
      - configserver:http://config-server:8888
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - StripPrefix=2   # it is not allowed /api/v1 in order service or any services where another api calling
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=X-Custom-Header, Aman
#                - RedirectTo=302,https://youtube.com   when we have to hit inventory then redirect to youtube website


server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka