
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/module8
spring.datasource.username=postgres
spring.datasource.password=3092

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

my.variable=dev
