spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 3092
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

server:
  port: 9011
  servlet:
    context-path: /orders

#eureka server config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:    # koi service down/fail hai to wait karega 5sec ke liye and automatic attempt lega 3 sec ke acoording par
    instances:
      inventoryRetry:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:     # set api hit limit for some time
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 5s   # Har 1 second baad 100 permits refill ho jayenge
        limitForPeriod: 3   #3 requests allowed
        timeoutDuration: 1s  #Agar permit available nahi hai to request 1 sec tak wait karegi.