spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/gitcoder-aman/ecommerce-config-server
          username: gitcoder-aman
          password: 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
          default-label: main
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka