INSERT INTO products (title, stock, price) VALUES
                                              ('Laptop', 15, 55000),
                                              ('Smartphone', 30, 22000),
                                              ('Headphones', 50, 1500),
                                              ('Keyboard', 25, 800),
                                              ('Mouse', 40, 500),
                                              ('Monitor', 10, 12000),
                                              ('Printer', 8, 9000),
                                              ('Tablet', 12, 18000),
                                              ('USB Drive', 60, 600),
                                              ('External Hard Disk', 20, 4500),
                                              ('Smart Watch', 18, 7000),
                                              ('Bluetooth Speaker', 35, 2500),
                                              ('Webcam', 22, 3200),
                                              ('Router', 14, 2800),
                                              ('Power Bank', 45, 1200),
                                              ('SSD 512GB', 16, 6500),
                                              ('RAM 16GB', 11, 5200),
                                              ('Graphics Card', 6, 35000),
                                              ('Microphone', 19, 2700),
                                              ('Cooling Fan', 28, 900);