spring:
  application:
    name: caching

  datasource:
    url: jdbc:postgresql://localhost:5432/Module4
    username: postgres
    password: 3092
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true       # show SQL queries in console
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Enable Redis caching
  cache:
    type: redis

  data:
    redis:
#      host: localhost
#      port: 6379
      host: redis-14818.crce292.ap-south-1-2.ec2.cloud.redislabs.com
      port: 14818
      password: sQFSNa6vmdPucs3omFvqTSzLN4r2IWZD
      database: 0
      timeout: 60000
      ssl:
        enabled: false

  redis:
    cache:
      time-to-live: 600000      # 10 minutes
      cache-null-values: false